### PR TITLE
Fix console resize (WinForms)

### PR DESCRIPTION
**Pull request by Tom-V**

### CODE REVIEW

**Comment by Tom-V** [comment]
Also added Java detector by using the registry, this will allow custom install paths.

**Comment by riking** [comment]
Please fix your newline characters, they make the diff ugly to look at.

**Comment by Tom-V** [comment]
was wondering why that happened, didn't think about newline chars

**Comment by riking** [comment]
there's a git config setting, core.autocrlf i believe. Google it / search on github help

**Comment by Tom-V** [comment]
This should fix it. (Still a noob at git, would be better if it was new pull request I think)

**Comment by Forkk** [comment]
I like the idea of checking the Java path via the registry. I'll make sure that gets implemented in MultiMC 4. (https://github.com/Forkk/MultiMC4)
As for this pull request, I've switched to Linux but I'll see if I feel like booting Windows and pulling this later. :)

**Comment by Forkk** [comment]
Actually I can just go ahead and have github merge it automatically. :P

**Pull request merged**
